### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Eiye1123** [javid-norouzi/SAR-Image-Despeckling-Using-CNN-#1]
Hello, dear boss, can you provide your data set? Thank you very much

**Comment by ShowStopperTheSecond** [comment]
Hi :) 
[Here](https://www.kaggle.com/datasets/requiemonk/sentinel12-image-pairs-segregated-by-terrain) is the link to data.
And [here](https://www.kaggle.com/code/javidtheimmortal/sar-image-despeckling-using-a-convolutional-neural]) you can view the notebook I ran on kaggle
