### ISSUE TITLE
Version Issues

### ISSUE THREAD

**Issue by jeonghomin** [javid-norouzi/SAR-Image-Despeckling-Using-CNN-#2]
Since this code has updated in 2017, I wonder if there is an updated version.

Or is there any requirements for tensorflow version or the others for this code?

**Comment by ShowStopperTheSecond** [comment]
Hi sorry for the late reply 
check out  the kaggle notebook here 
https://www.kaggle.com/code/javidtheimmortal/sar-image-despeckling-using-a-convolutional-neural
