### ISSUE TITLE
Error in demonstrate train_generator on Colab

### ISSUE THREAD

**Issue by Mohamed-DL** [javid-norouzi/SAR-Image-Despeckling-Using-CNN-#3]
Hi, thank you for sharing the code. I have an issue demonstrating the train generator on colab, it shows the error: TypeError: Invalid shape (64, 64, 1) for image data. I can't train the model because this error. Would you please have a look at to screenshot, and let me know how you overcome it on Colab?

Thank you

![error](https://user-images.githubusercontent.com/62818907/218316897-c8f9f66e-7fe2-4f37-ae6f-8446bb316e11.PNG)

**Comment by ShowStopperTheSecond** [comment]
Hi :) 
Why don't you run the notebook I shared in kaggle?

**Comment by ShowStopperTheSecond** [comment]
For matplotlib.pyplot to show an image it must be either a 2D array or it can be a 3D array with 3 or 4 channels. take a look at the the if statement before the exception

**Comment by Mohamed-DL** [comment]
Thank you. Kaggle notebook runs with 300 EPOCHS maximum before having a memory error and code crash.  I would ask if the model (saved_model_14000912.h5) you shared is a result of 100 epochs or 2000 epochs?

**Comment by ShowStopperTheSecond** [comment]
I'm not quite sure why you're having such an issue. But the weights I've shared are for 2000 epochs

**Comment by Mohamed-DL** [comment]
Thank you for your answer. I am closing the issue.
